# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Despliegue Proyecto Curso ASP.NET!!

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Construcción del Proyecto y ejecución de pruebas unitarias
    runs-on: ubuntu-latest
      #ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o publish
    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        path: publish  
  docker:
    name: Poner el contenido del proyecto en un contenedor Docker
    runs-on: ubuntu-latest
    needs: [build]
    steps:     
      - uses: actions/checkout@v3
      - name: Docker build
        run: docker image build -f Dockerfile -t proyectocursonet .
      - name: Save Image
        run: docker save -o proyectocursonet.tar proyectocursonet
      - name: Upload
        uses: actions/upload-artifact@v3
        with: 
          path: proyectocursonet.tar
  storage:
    name: File Storage
    runs-on: self-hosted
    needs: [docker]
    steps:
      - name: Descargar archivos 1
        uses: actions/download-artifact@v3
        with: 
          path: publish
      - name: Descargar archivos 2         
        uses: actions/download-artifact@v3
        with: 
          path: proyectocursonet.tar
      - name: Mostrar archivos
        shell: bash
        run: ls -R publish/ 
      - name: Copiar archivos a destino
        shell: bash
        run: cp -R publish/artifact/* /home/jlopezh73/Publish
      - name: Crear Imagen de Docker desde archivo
        shell: bash
        run: sudo docker load -i proyectocursonet.tar/artifact/proyectocursonet.tar
